In [13]:
import numpy as np
import scipy

from graspologic.inference import latent_position_test
from graspologic.embed import AdjacencySpectralEmbed, LaplacianSpectralEmbed
from graspologic.simulations import er_np, sbm, rdpg
from graspologic.utils import symmetrize
from graspologic.plot import heatmap, pairplot
from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns

from sknetwork.data import erdos_renyi, painters, movie_actor
from sknetwork.embedding import Spectral, SVD
from sknetwork.visualization import svg_graph, svg_digraph, svg_bigraph
from IPython.display import SVG
%matplotlib inline

In [23]:
X = np.random.uniform(low=0.1, high=1, size=(100, 1))
print(X)
A = rdpg(X)
print(A)

[[0.46690926]
 [0.32045551]
 [0.58897824]
 [0.31321373]
 [0.55804153]
 [0.35181254]
 [0.48740873]
 [0.63637354]
 [0.40292413]
 [0.20304593]
 [0.67904304]
 [0.23980713]
 [0.57845896]
 [0.56315158]
 [0.10368417]
 [0.86477683]
 [0.64213802]
 [0.84438898]
 [0.9908338 ]
 [0.7416438 ]
 [0.62789041]
 [0.57943699]
 [0.30813615]
 [0.37015883]
 [0.41026996]
 [0.86318147]
 [0.53765677]
 [0.50460601]
 [0.29152278]
 [0.93147228]
 [0.19710716]
 [0.18954862]
 [0.12986419]
 [0.59544198]
 [0.51193986]
 [0.34652226]
 [0.47392117]
 [0.47118458]
 [0.80852531]
 [0.24875762]
 [0.59067262]
 [0.64979491]
 [0.59463637]
 [0.58508844]
 [0.69248188]
 [0.57991973]
 [0.51140116]
 [0.86024915]
 [0.64483514]
 [0.86361136]
 [0.41492382]
 [0.25155864]
 [0.86855914]
 [0.61123586]
 [0.61253375]
 [0.34572876]
 [0.13016568]
 [0.7431326 ]
 [0.4941046 ]
 [0.36175916]
 [0.91875584]
 [0.74976065]
 [0.81810616]
 [0.46131952]
 [0.42733986]
 [0.551194  ]
 [0.4936161 ]
 [0.50900319]
 [0.53070478]
 [0.33365412]
 [0.73258886]
 [0.96

In [24]:
ase = AdjacencySpectralEmbed(n_components=1)
Y=ase.fit_transform(A)
print(Y)
print(np.linalg.norm((Y-X), ord='fro'))

[[0.52285076]
 [0.20514029]
 [0.65814063]
 [0.31857999]
 [0.61671533]
 [0.51790728]
 [0.60583201]
 [0.60109352]
 [0.44153985]
 [0.19264921]
 [0.72463382]
 [0.20917074]
 [0.50178788]
 [0.5112502 ]
 [0.08301728]
 [0.70678167]
 [0.65352903]
 [0.95879255]
 [1.0370526 ]
 [0.72732118]
 [0.63716426]
 [0.59755821]
 [0.29258961]
 [0.41491474]
 [0.40385293]
 [0.8086927 ]
 [0.56308069]
 [0.52131234]
 [0.36483317]
 [0.89385634]
 [0.10561762]
 [0.17350164]
 [0.13187062]
 [0.602626  ]
 [0.44832505]
 [0.41230144]
 [0.54491739]
 [0.48981171]
 [0.8921018 ]
 [0.17813599]
 [0.5159387 ]
 [0.75301717]
 [0.69482959]
 [0.55391393]
 [0.53397693]
 [0.5487905 ]
 [0.65809902]
 [0.85301954]
 [0.66954511]
 [0.78977625]
 [0.35967034]
 [0.11740411]
 [0.89113757]
 [0.67950976]
 [0.56682243]
 [0.31132264]
 [0.10429247]
 [0.68283319]
 [0.61631568]
 [0.32949438]
 [0.88558924]
 [0.82605343]
 [0.74123477]
 [0.47022718]
 [0.45077342]
 [0.64713213]
 [0.56742076]
 [0.58211639]
 [0.5608682 ]
 [0.35407184]
 [0.74790284]
 [1.00

In [25]:
svd = SVD(1)
X2 = svd.fit_transform(A)
print(X2)
print(np.linalg.norm((X2-X), ord='fro'))

[[-3.03978522]
 [-1.19973203]
 [-3.81929647]
 [-1.8575769 ]
 [-3.58094965]
 [-3.01274741]
 [-3.51823204]
 [-3.49054577]
 [-2.56962505]
 [-1.12468602]
 [-4.20081058]
 [-1.22241041]
 [-2.91907799]
 [-2.9736351 ]
 [-0.48571476]
 [-4.09917919]
 [-3.792834  ]
 [-5.53857151]
 [-5.9806631 ]
 [-4.21613099]
 [-3.69866251]
 [-3.47164804]
 [-1.70790743]
 [-2.41695986]
 [-2.35227117]
 [-4.68294794]
 [-3.27181181]
 [-3.03205826]
 [-2.1254402 ]
 [-5.16985455]
 [-0.61742523]
 [-1.01332843]
 [-0.77184957]
 [-3.49955601]
 [-2.61016571]
 [-2.40115187]
 [-3.16808207]
 [-2.85043765]
 [-5.15984703]
 [-1.04261312]
 [-3.00103254]
 [-4.36276212]
 [-4.03055957]
 [-3.21932153]
 [-3.10521371]
 [-3.19015947]
 [-3.82038027]
 [-4.93531211]
 [-3.88515866]
 [-4.57594621]
 [-2.09642662]
 [-0.68617877]
 [-5.15233534]
 [-3.94147504]
 [-3.29510465]
 [-1.81557441]
 [-0.60971743]
 [-3.95960062]
 [-3.57754344]
 [-1.92271811]
 [-5.11999035]
 [-4.77998901]
 [-4.29571108]
 [-2.73672877]
 [-2.6243231 ]
 [-3.75624952]
 [-3.29812