In [1]:
import numpy as np
import scipy

from graspologic.inference import latent_position_test
from graspologic.embed import AdjacencySpectralEmbed, LaplacianSpectralEmbed
from graspologic.simulations import er_np, sbm, rdpg
from graspologic.utils import symmetrize
from graspologic.plot import heatmap, pairplot
from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns

from sknetwork.data import erdos_renyi, painters, movie_actor
from sknetwork.embedding import Spectral, SVD
from sknetwork.visualization import svg_graph, svg_digraph, svg_bigraph
from IPython.display import SVG
%matplotlib inline

In [12]:
X = np.random.uniform(low=0.1, high=1, size=(20, 1))
A = rdpg(X)

In [13]:
ase = AdjacencySpectralEmbed(n_components=1)
X1 = ase.fit_transform(A)
svd = SVD(1)
X2 = svd.fit_transform(A)
print(X1)
print(X2)
print(np.linalg.norm(X1, axis=0))
print(np.linalg.norm(X2, axis=0))

[[1.01539536]
 [0.94936968]
 [0.76407917]
 [0.66831337]
 [0.6209419 ]
 [0.94668067]
 [0.21368968]
 [0.5866866 ]
 [0.63328241]
 [0.63109462]
 [0.65015278]
 [0.06871388]
 [1.00199133]
 [0.11055673]
 [0.44686379]
 [0.35829739]
 [0.17014388]
 [0.18291176]
 [0.92261701]
 [1.05732585]]
[[2.8813641 ]
 [2.70608964]
 [2.21077559]
 [1.94083142]
 [1.81138046]
 [2.70970259]
 [0.63562527]
 [1.7154319 ]
 [1.84642667]
 [1.82505601]
 [1.89460229]
 [0.2091248 ]
 [2.84108461]
 [0.3301623 ]
 [1.31978194]
 [1.06437379]
 [0.51058415]
 [0.54793784]
 [2.63087012]
 [3.00023427]]
[3.03924572]
[8.72711412]


In [14]:
lse = LaplacianSpectralEmbed(n_components=1)
X1 = lse.fit_transform(A)
spectral = Spectral(1)
X2 = spectral.fit_transform(A)
print(X1)
print(X2)
print(np.linalg.norm(X1))
print(np.linalg.norm(X2))

[[0.29704423]
 [0.284398  ]
 [0.24253575]
 [0.24253583]
 [0.22687129]
 [0.27116313]
 [0.12126744]
 [0.21004199]
 [0.22687128]
 [0.24253567]
 [0.22687144]
 [0.08574943]
 [0.29704405]
 [0.08574936]
 [0.19174125]
 [0.1714987 ]
 [0.12126785]
 [0.12126797]
 [0.28439824]
 [0.29704423]]
[[-1.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]]
0.999999999999909
4.47213595499958
